  plugins:
    # https://github.com/jest-community/eslint-plugin-jest
    - jest

  extends:
    - 'airbnb-base'
    - 'plugin:jest/recommended'

  rules:
    no-console: 0
    semi: 
      - warn
      - always
    quotes:
      - warn
      - single
    indent: 1
    no-plusplus: 0
    import/extensions:
      - error
      - ignorePackages
      - js: always

  reportUnusedDisableDirectives: true