name: test-and-coverage

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install, build, test
      - run: |
          make install
          make test
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
        with:
          coverageCommand: make test-coverage
