name: coverage-check

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        uses: actions/setup-node@v3
      - run: |
          make install
          make test
          make lint
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
        with:
          coverageCommand: make test-coverage