name: test-check

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: make install

      - name: Teset
        run: make test
